export const GET_TRENDING_MOVIES = 'GET_TRENDING_MOVIES'
export const SET_LOADING = 'SET_LOADING'
export const SET_TRENDING_MOVIES = 'SET_TRENDING_MOVIES'
export const GET_SEARCH_MOVIES = 'GET_SEARCH_MOVIES'
